ALTER TABLE users ADD COLUMN salt VARCHAR(64);
ALTER TABLE users ADD COLUMN hash VARCHAR(128);
ALTER TABLE users ADD COLUMN hash_legacy VARCHAR(128);
ALTER TABLE users ADD COLUMN needs_migration BOOLEAN DEFAULT FALSE;